use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    configure_windows_stack();

    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let fixtures = manifest_dir.join("tests/fixtures/composer");
    let ported_file = fixtures.join("ported.txt");
    println!("cargo:rerun-if-changed={}", fixtures.display());

    let ported = read_list(&ported_file);
    let mut fixture_paths = Vec::new();
    collect_tests(&fixtures, &fixtures, &mut fixture_paths);
    fixture_paths.sort();

    for path in &ported {
        if !fixture_paths.iter().any(|fixture| fixture == path) {
            panic!("ported Composer fixture does not exist: {path}");
        }
    }

    let mut generated = String::from("// Generated by crates/riff/build.rs.\n");
    let mut names = HashSet::new();
    for relative in fixture_paths {
        let name = format!("composer_{}", test_name(&relative));
        assert!(
            names.insert(name.clone()),
            "duplicate generated test name: {name}"
        );
        let ignored = if ported.contains(&relative) {
            String::new()
        } else {
            "#[ignore = \"pending Composer compatibility port\"]\n".to_string()
        };
        generated.push_str(&format!(
            "#[test]\n{ignored}fn {name}() {{\n    support::composer_fixture::run(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/tests/fixtures/composer/{relative}\")));\n}}\n\n"
        ));
    }

    let output = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("composer_fixture_cases.rs");
    fs::write(output, generated).unwrap();
}

fn configure_windows_stack() {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    // Windows executables reserve a 1 MiB main-thread stack by default. The
    // dependency solver can exceed that in debug builds, while the same work
    // fits within the conventional 8 MiB Unix main stack.
    match env::var("CARGO_CFG_TARGET_ENV").as_deref() {
        Ok("msvc") => println!("cargo:rustc-link-arg-bins=/STACK:8388608"),
        Ok("gnu") => println!("cargo:rustc-link-arg-bins=-Wl,--stack,8388608"),
        _ => {}
    }
}

fn read_list(path: &Path) -> HashSet<String> {
    fs::read_to_string(path)
        .unwrap_or_default()
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(str::to_string)
        .collect()
}

fn collect_tests(root: &Path, directory: &Path, output: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(directory) else {
        return;
    };
    for entry in entries {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect_tests(root, &path, output);
        } else if path.extension().and_then(|extension| extension.to_str()) == Some("test") {
            output.push(
                path.strip_prefix(root)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
}

fn test_name(path: &str) -> String {
    path.chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect::<String>()
        .trim_end_matches('_')
        .to_string()
}
