[workspace]
resolver = "2"
members = [
    "crates/riff",
    "crates/riff-core",
    "crates/riff-semver",
    "crates/riff-spdx",
]

[workspace.package]
version = "0.0.5"
edition = "2021"
license = "MIT"
repository = "https://github.com/shyim/riff"

[profile.dev]
debug = 1

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.profiling]
inherits = "release"
debug = 1
strip = false
