#!/usr/bin/env bash

set -euo pipefail

TAG="${TAG:?TAG is required, for example v0.0.4}"
MACOS_ARM64_SHA256="${MACOS_ARM64_SHA256:?MACOS_ARM64_SHA256 is required}"
MACOS_X86_64_SHA256="${MACOS_X86_64_SHA256:?MACOS_X86_64_SHA256 is required}"
LINUX_ARM64_SHA256="${LINUX_ARM64_SHA256:?LINUX_ARM64_SHA256 is required}"
LINUX_X86_64_SHA256="${LINUX_X86_64_SHA256:?LINUX_X86_64_SHA256 is required}"

if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "TAG must match vMAJOR.MINOR.PATCH" >&2
  exit 1
fi

for checksum in \
  "$MACOS_ARM64_SHA256" \
  "$MACOS_X86_64_SHA256" \
  "$LINUX_ARM64_SHA256" \
  "$LINUX_X86_64_SHA256"
do
  if [[ ! "$checksum" =~ ^[0-9a-f]{64}$ ]]; then
    echo "Homebrew asset checksums must be lowercase SHA-256 values" >&2
    exit 1
  fi
done

VERSION="${TAG#v}"
RELEASE_URL="https://github.com/shyim/riff/releases/download/${TAG}"

cat <<FORMULA
# typed: false
# frozen_string_literal: true

# This file is generated by shyim/riff. Do not edit it in the tap.
class PhpRiff < Formula
  desc "Fast, standalone Composer-compatible package manager"
  homepage "https://github.com/shyim/riff"
  version "${VERSION}"
  license "MIT"

  depends_on "php"

  conflicts_with "riff", because: "both install a riff executable"

  on_macos do
    on_arm do
      url "${RELEASE_URL}/riff-${TAG}-aarch64-apple-darwin.tar.gz"
      sha256 "${MACOS_ARM64_SHA256}"
    end

    on_intel do
      url "${RELEASE_URL}/riff-${TAG}-x86_64-apple-darwin.tar.gz"
      sha256 "${MACOS_X86_64_SHA256}"
    end
  end

  on_linux do
    on_arm do
      url "${RELEASE_URL}/riff-${TAG}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_ARM64_SHA256}"
    end

    on_intel do
      url "${RELEASE_URL}/riff-${TAG}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_X86_64_SHA256}"
    end
  end

  def install
    bin.install "riff"
    generate_completions_from_executable(bin/"riff", "completion")
  end

  test do
    (testpath/"composer.json").write <<~JSON
      {
        "name": "homebrew/riff-test",
        "require": {}
      }
    JSON

    system bin/"riff", "install", "--no-audit", "--no-interaction", "--no-plugins", "--no-scripts"
    assert_path_exists testpath/"composer.lock"
  end
end
FORMULA
